name: Ansible Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'
      - 'README.md'
      - '.github/workflows/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE.md'
      - 'nomakcooper/collection/README.md'
      - 'nomakcooper/collection/changelogs/**'
      - 'nomakcooper/collection/changelogs/CHANGELOG.rst'
      - 'docs/**'
  schedule:
    - cron: '0 6 * * *'
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  sanity:
    name: Sanity (Ⓐ${{ matrix.ansible }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ansible:
          - '2.18'
    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      - name: Fetch base branch (main)
        run: git fetch origin main:main

      - name: Perform sanity testing
        uses: ansible-community/ansible-test-gh-action@release/v1.16
        with:
          ansible-core-version: stable-${{ matrix.ansible }}
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          coverage: ${{ github.event_name == 'schedule' && 'always' || 'never' }}
          testing-type: sanity
          collection-root: nomakcooper/collection
          collection-src-directory: ${{ github.workspace }}
          pre-test-cmd: pip install -r meta/requirements.txt
          pull-request-change-detection: 'true'

      - name: Upload sanity test summary
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: test-summary-${{ github.job }}-${{ matrix.ansible }}
          path: $GITHUB_STEP_SUMMARY

  integration:
    name: Integration (Ⓐ${{ matrix.ansible }}+py${{ matrix.python }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ansible:
          - devel
        python:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
        include:
          - ansible: stable-2.16
            python: '3.9'
          - ansible: stable-2.16
            python: '3.10'
          - ansible: stable-2.16
            python: '3.11'
          - ansible: stable-2.16
            python: '3.12'
          - ansible: stable-2.17
            python: '3.9'
          - ansible: stable-2.17
            python: '3.10'
          - ansible: stable-2.17
            python: '3.11'
          - ansible: stable-2.17
            python: '3.12'
          - ansible: stable-2.18
            python: '3.9'
          - ansible: stable-2.18
            python: '3.10'
          - ansible: stable-2.18
            python: '3.11'
          - ansible: stable-2.18
            python: '3.12'
    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      - name: Fetch base branch (main)
        run: git fetch origin main:main

      - name: Perform integration testing
        uses: ansible-community/ansible-test-gh-action@release/v1.16
        with:
          ansible-core-version: ${{ matrix.ansible }}
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          target-python-version: ${{ matrix.python }}
          testing-type: integration
          collection-root: nomakcooper/collection
          collection-src-directory: ${{ github.workspace }}
          pre-test-cmd: pip install -r meta/requirements.txt
          test-deps: ansible.netcommon
          pull-request-change-detection: 'true'
          integration-diff: 'false'

      - name: Upload integration test summary
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: test-summary-${{ github.job }}-${{ matrix.ansible }}-py${{ matrix.python }}
          path: $GITHUB_STEP_SUMMARY

  check:
    name: Check
    if: always()
    needs:
      - sanity
      - integration
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        continue-on-error: true
        with:
          jobs: ${{ toJSON(needs) }}

      - name: Download test summaries
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/download-artifact@v4
        with:
          path: test-summaries

      - name: Aggregate test summaries
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          # Combine all test summary files (assuming they are plain text)
          find test-summaries -type f -exec cat {} + > combined-summary.txt
          echo "Combined test summary:"
          cat combined-summary.txt

      - name: Check for errors in aggregated test summary
        id: check_errors
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          # Extract the first occurrence of a number preceding the word "failed"
          fail_count=$(grep -oP '\d+(?=\s+failed)' combined-summary.txt | head -n1)
          echo "fail_count is: $fail_count"
          if [ -z "$fail_count" ]; then
            echo "errors_found=false" >> $GITHUB_OUTPUT
          elif [ "$fail_count" -gt 0 ]; then
            echo "errors_found=true" >> $GITHUB_OUTPUT
          else
            echo "errors_found=false" >> $GITHUB_OUTPUT
          fi

      - name: Get aggregated test summary
        id: get_test_summary
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "test_summary<<EOF" >> $GITHUB_OUTPUT
          cat combined-summary.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create or update PR comment with aggregated test summary
        if: ${{ github.event_name == 'pull_request' && steps.check_errors.outputs.errors_found == 'true' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Combined Test Summary
            ${{ steps.get_test_summary.outputs.test_summary }}