name: Generate Changelog

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Towncrier
        run: pip install towncrier

      - name: Generate Changelog
        run: towncrier --version "${{ github.event.release.tag_name }}"

      - name: Commit and Push Changelog Update
        run: |
          git config user.name "github-actions[releasebot]"
          git config user.email "github-actions[releasebot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog for release ${{ github.event.release.tag_name }} [skip ci]" || echo "No changes to commit"
          git push
