name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'
      - 'README.md'
      - '.github/workflows/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE.md'
      - 'nomakcooper/collection/README.md'
      - 'nomakcooper/collection/changelogs/**'
      - 'nomakcooper/collection/changelogs/CHANGELOG.rst'
      - 'built-docs/**'
  pull_request:
  schedule:
    - cron: '0 6 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  sanity:
    name: Sanity (Ⓐ${{ matrix.ansible }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ansible:
          - stable-2.18
          - devel
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Perform sanity testing
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: ${{ matrix.ansible }}
          testing-type: sanity
          collection-root: nomakcooper/collection
          sanity-skip-tests: "import, runtime-metadata"
          pre-test-cmd: pip install -r meta/requirements.txt
          pull-request-change-detection: true

  integration:
    name: Integration (Ⓐ${{ matrix.ansible }}+py${{ matrix.python }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ansible:
          - devel
        python:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
        include:
          - ansible: stable-2.16
            python: '3.6'
          - ansible: stable-2.16
            python: '3.7'
          - ansible: stable-2.16
            python: '3.8'
          - ansible: stable-2.16
            python: '3.9'
          - ansible: stable-2.16
            python: '3.10'
          - ansible: stable-2.16
            python: '3.11'
          - ansible: stable-2.16
            python: '3.12'
          - ansible: stable-2.17
            python: '3.7'
          - ansible: stable-2.17
            python: '3.8'
          - ansible: stable-2.17
            python: '3.9'
          - ansible: stable-2.17
            python: '3.10'
          - ansible: stable-2.17
            python: '3.11'
          - ansible: stable-2.17
            python: '3.12'
          - ansible: stable-2.18
            python: '3.8'
          - ansible: stable-2.18
            python: '3.9'
          - ansible: stable-2.18
            python: '3.10'
          - ansible: stable-2.18
            python: '3.11'
          - ansible: stable-2.18
            python: '3.12'
          - ansible: stable-2.18
            python: '3.13'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Perform integration testing
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: ${{ matrix.ansible }}
          target-python-version: ${{ matrix.python }}
          testing-type: integration
          collection-root: nomakcooper/collection
          pre-test-cmd: pip install -r meta/requirements.txt
          test-deps: ansible.netcommon
          pull-request-change-detection: true

  check:
    name: Check
    if: always()
    needs:
      - sanity
      - integration
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}