name: Auto Issues

on:
  issues:
    types: [opened]

jobs:
  process_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Process Issue Inline
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const issueBody = issue.body || "";
            const labelsToAdd = ["needs_triage", "module"];

            if (issueBody.includes("Bug Report")) {
              labelsToAdd.push("bug");
            } else if (issueBody.includes("Feature Idea") || issueBody.includes("✨ Feature request")) {
              labelsToAdd.push("feature");
            }

            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              labels: labelsToAdd,
            });

            const componentSectionRegex = /#####\s*COMPONENT NAME\s*\n\s*([a-zA-Z0-9_\-]+\.py)/i;
            let componentName = "COMPONENT_NAME";
            const match = issueBody.match(componentSectionRegex);
            if (match && match[1]) {
              componentName = match[1].trim();
            }

            let componentPath = componentName;
            if (componentName.endsWith('.py')) {
              componentPath = `nomakcooper/collection/plugins/modules/${componentName}`;
            }

            const commentBody = `Files identified in the description:\n\n[${componentName}](${componentPath})`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: commentBody,
            });
