name: Auto PR

on:
  pull_request:
    types: [opened]

jobs:
  process_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Process PR Inline
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const prBody = pr.body || "";
            
            // --- Determine labels based on checkboxes in ISSUE TYPE section ---
            // The PR template contains checkboxes like:
            // - [ ] Bugfix Pull Request
            // - [ ] Feature Pull Request
            // - [ ] New Module/Plugin Pull Request
            // We'll assign additional labels based on which box is checked.
            const labelsToAdd = ["needs_triage", "module"]; // Always add these labels

            // Check for a checked box. A simple way is to look for "- [x] <Label>" in the PR body.
            if (prBody.match(/- \[x\] Bugfix Pull Request/i)) {
              labelsToAdd.push("bug");
            }
            if (prBody.match(/- \[x\] Feature Pull Request/i)) {
              labelsToAdd.push("feature");
            }
            if (prBody.match(/- \[x\] New Module\/Plugin Pull Request/i)) {
              labelsToAdd.push("new_module");
            }
            
            // Add labels to the PR.
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              labels: labelsToAdd,
            });