name: Sync Ansible Galaxy Version to GitHub Releases

# Run on a schedule (here: every hour) or manually.
on:
  workflow_dispatch:

jobs:
  sync-release:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Get the latest version from Ansible Galaxy.
      - name: Fetch Ansible Galaxy Latest Version
        id: galaxy
        run: |
          echo "Querying Ansible Galaxy v3 API for published versions..."
          response=$(curl -s -H "Accept: application/json" "https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/index/nomakcooper/collection/")
          echo "$response" > galaxy_response.json
          echo "Galaxy API response:"
          cat galaxy_response.json
          PUBLISHED_VERSION=$(echo "$response" | jq -r '.highest_version.version')
          echo "Latest Galaxy version: $PUBLISHED_VERSION"
          echo "version=$PUBLISHED_VERSION" >> $GITHUB_OUTPUT

      # Step 2: Get the latest GitHub release version.
      - name: Get Latest GitHub Release Version
        id: gh_release
        uses: actions/github-script@v6
        with:
          script: |
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1,
            });
            if (releases.data.length > 0) {
              return releases.data[0].tag_name;
            }
            return "";
          result-encoding: string

      # Optional: Output both versions for debugging.
      - name: Debug Versions
        run: |
          echo "Ansible Galaxy version: ${{ steps.galaxy.outputs.version }}"
          echo "GitHub release version: ${{ steps.gh_release.outputs.result }}"

      # Step 3: If versions differ, create a new GitHub release.
      - name: Create New GitHub Release If Needed
        if: steps.galaxy.outputs.version != steps.gh_release.outputs.result
        uses: actions/github-script@v6
        with:
          script: |
            const newVersion = process.env.NEW_VERSION;
            console.log(`Creating GitHub release for version: ${newVersion}`);
            const releaseResponse = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: newVersion,
              name: `${newVersion}`,
              body: `Automated release: Ansible Galaxy collection updated to version ${newVersion}.\n\nRelease changelog at [CHANGELOG.rst](nomakcooper/collection/CHANGELOG.rst)`,
              draft: false,
              prerelease: false
            });
            console.log("Release created at:", releaseResponse.data.html_url);
        env:
          NEW_VERSION: ${{ steps.galaxy.outputs.version }}

